2024-06-18 15:31:21 | INFO | model_worker | args: Namespace(host='localhost', port=41002, worker_address='http://localhost:41002', controller_address='http://localhost:41001', model_path='/home/c205/workspace/models/HuatuoGPT2-13B/', revision='main', device='cuda', gpus=None, num_gpus=1, max_gpu_memory=None, dtype=None, load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-06-18 15:31:21 | INFO | model_worker | Loading the model ['HuatuoGPT2-13B'] on worker 5d386aa3 ...
2024-06-18 15:31:21 | ERROR | stderr | Traceback (most recent call last):
2024-06-18 15:31:21 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-18 15:31:21 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 414, in <module>
2024-06-18 15:31:21 | ERROR | stderr |     args, worker = create_model_worker()
2024-06-18 15:31:21 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 385, in create_model_worker
2024-06-18 15:31:21 | ERROR | stderr |     worker = ModelWorker(
2024-06-18 15:31:21 | ERROR | stderr |              ^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 77, in __init__
2024-06-18 15:31:21 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-06-18 15:31:21 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 362, in load_model
2024-06-18 15:31:21 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-06-18 15:31:21 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 97, in load_model
2024-06-18 15:31:21 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-06-18 15:31:21 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 865, in from_pretrained
2024-06-18 15:31:21 | ERROR | stderr |     return tokenizer_class.from_pretrained(
2024-06-18 15:31:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2110, in from_pretrained
2024-06-18 15:31:21 | ERROR | stderr |     return cls._from_pretrained(
2024-06-18 15:31:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2336, in _from_pretrained
2024-06-18 15:31:21 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-06-18 15:31:21 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/.cache/huggingface/modules/transformers_modules/tokenization_baichuan.py", line 71, in __init__
2024-06-18 15:31:21 | ERROR | stderr |     super().__init__(
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 367, in __init__
2024-06-18 15:31:21 | ERROR | stderr |     self._add_tokens(
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
2024-06-18 15:31:21 | ERROR | stderr |     current_vocab = self.get_vocab().copy()
2024-06-18 15:31:21 | ERROR | stderr |                     ^^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/.cache/huggingface/modules/transformers_modules/tokenization_baichuan.py", line 105, in get_vocab
2024-06-18 15:31:21 | ERROR | stderr |     vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
2024-06-18 15:31:21 | ERROR | stderr |                                                              ^^^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr |   File "/home/c205/.cache/huggingface/modules/transformers_modules/tokenization_baichuan.py", line 101, in vocab_size
2024-06-18 15:31:21 | ERROR | stderr |     return self.sp_model.get_piece_size()
2024-06-18 15:31:21 | ERROR | stderr |            ^^^^^^^^^^^^^
2024-06-18 15:31:21 | ERROR | stderr | AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'
