2024-06-20 10:57:51 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8003, controller_address='http://localhost:41001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 10:57:51 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m6025[0m]
2024-06-20 10:57:51 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 10:57:51 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 10:57:51 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8003[0m (Press CTRL+C to quit)
2024-06-20 10:59:14 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 10:59:14 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 10:59:14 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 10:59:14 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m6025[0m]
2024-06-20 10:59:14 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 10:59:14 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 10:59:14 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 10:59:14 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 10:59:14 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 10:59:14 | ERROR | stderr | 
2024-06-20 10:59:14 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 10:59:14 | ERROR | stderr | 
2024-06-20 10:59:14 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 10:59:14 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 10:59:14 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 10:59:14 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 10:59:14 | ERROR | stderr |     server.run()
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 10:59:14 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 10:59:14 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 10:59:14 | ERROR | stderr |     return runner.run(main)
2024-06-20 10:59:14 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 10:59:14 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 10:59:14 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 10:59:14 | ERROR | stderr | KeyboardInterrupt
2024-06-20 10:59:25 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8003, controller_address='http://localhost:41001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 10:59:25 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m7880[0m]
2024-06-20 10:59:25 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 10:59:25 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 10:59:25 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8003[0m (Press CTRL+C to quit)
2024-06-20 10:59:46 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8000, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 10:59:46 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m9914[0m]
2024-06-20 10:59:46 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 10:59:46 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 10:59:46 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8000[0m (Press CTRL+C to quit)
2024-06-20 11:00:38 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 11:00:38 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 11:00:38 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 11:00:38 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m7880[0m]
2024-06-20 11:00:38 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 11:00:38 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 11:00:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:00:38 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 11:00:38 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 11:00:38 | ERROR | stderr | 
2024-06-20 11:00:38 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 11:00:38 | ERROR | stderr | 
2024-06-20 11:00:38 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:00:38 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 11:00:38 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 11:00:38 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 11:00:38 | ERROR | stderr |     server.run()
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 11:00:38 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 11:00:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 11:00:38 | ERROR | stderr |     return runner.run(main)
2024-06-20 11:00:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 11:00:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 11:00:38 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 11:00:38 | ERROR | stderr | KeyboardInterrupt
2024-06-20 11:00:49 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8003, controller_address='http://localhost:41001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 11:00:49 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m11298[0m]
2024-06-20 11:00:49 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 11:00:49 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 11:00:49 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8003[0m (Press CTRL+C to quit)
2024-06-20 11:06:57 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 11:06:57 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m16708[0m]
2024-06-20 11:06:57 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 11:06:57 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 11:06:57 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 11:13:18 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33204 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 11:13:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34324 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 11:14:41 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 11:14:41 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 11:14:41 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 11:14:41 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m16708[0m]
2024-06-20 11:14:41 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 11:14:41 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 11:14:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:14:41 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 11:14:41 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 11:14:41 | ERROR | stderr | 
2024-06-20 11:14:41 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 11:14:41 | ERROR | stderr | 
2024-06-20 11:14:41 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:14:41 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 11:14:41 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 11:14:41 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 11:14:41 | ERROR | stderr |     server.run()
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 11:14:41 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 11:14:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 11:14:41 | ERROR | stderr |     return runner.run(main)
2024-06-20 11:14:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 11:14:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 11:14:41 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 11:14:41 | ERROR | stderr | KeyboardInterrupt
2024-06-20 11:24:17 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 11:24:17 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m22572[0m]
2024-06-20 11:24:17 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 11:24:17 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 11:24:17 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 11:28:33 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 11:28:33 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 11:28:33 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 11:28:33 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m22572[0m]
2024-06-20 11:28:33 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 11:28:33 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 11:28:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:28:33 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 11:28:33 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 11:28:33 | ERROR | stderr | 
2024-06-20 11:28:33 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 11:28:33 | ERROR | stderr | 
2024-06-20 11:28:33 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:28:33 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 11:28:33 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 11:28:33 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 11:28:33 | ERROR | stderr |     server.run()
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 11:28:33 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 11:28:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 11:28:33 | ERROR | stderr |     return runner.run(main)
2024-06-20 11:28:33 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 11:28:33 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 11:28:33 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 11:28:33 | ERROR | stderr | KeyboardInterrupt
2024-06-20 11:28:44 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 11:28:44 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m25433[0m]
2024-06-20 11:28:44 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 11:28:44 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 11:28:44 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 11:28:51 | INFO | stdout | [32mINFO[0m:     127.0.0.1:55394 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 11:29:47 | INFO | stdout | [32mINFO[0m:     127.0.0.1:35744 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 11:31:58 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 11:31:58 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 11:31:58 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 11:31:58 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m25433[0m]
2024-06-20 11:31:58 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 11:31:58 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 11:31:58 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:31:58 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 11:31:58 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 11:31:58 | ERROR | stderr | 
2024-06-20 11:31:58 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 11:31:58 | ERROR | stderr | 
2024-06-20 11:31:58 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 11:31:58 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 11:31:58 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 11:31:58 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 11:31:58 | ERROR | stderr |     server.run()
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 11:31:58 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 11:31:58 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 11:31:58 | ERROR | stderr |     return runner.run(main)
2024-06-20 11:31:58 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 11:31:58 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 11:31:58 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 11:31:58 | ERROR | stderr | KeyboardInterrupt
2024-06-20 11:32:00 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 11:32:00 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m27207[0m]
2024-06-20 11:32:00 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 11:32:00 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 11:32:00 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 12:13:46 | INFO | stdout | [32mINFO[0m:     127.0.0.1:57258 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:14:09 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45076 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:21:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43148 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:22:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43770 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:22:41 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 12:22:42 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 12:22:42 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 12:22:42 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m27207[0m]
2024-06-20 12:22:42 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 12:22:42 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 12:22:42 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:22:42 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 12:22:42 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 12:22:42 | ERROR | stderr | 
2024-06-20 12:22:42 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 12:22:42 | ERROR | stderr | 
2024-06-20 12:22:42 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:22:42 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 12:22:42 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 12:22:42 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 12:22:42 | ERROR | stderr |     server.run()
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 12:22:42 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 12:22:42 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 12:22:42 | ERROR | stderr |     return runner.run(main)
2024-06-20 12:22:42 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 12:22:42 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 12:22:42 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 12:22:42 | ERROR | stderr | KeyboardInterrupt
2024-06-20 12:22:44 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 12:22:44 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m31418[0m]
2024-06-20 12:22:44 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 12:22:44 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 12:22:44 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 12:23:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:57788 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:24:41 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42864 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:25:12 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42270 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:25:18 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42286 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:25:22 | INFO | stdout | [32mINFO[0m:     127.0.0.1:58202 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:25:32 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34880 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:27:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51182 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:27:26 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51190 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:27:28 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50394 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:27:36 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50408 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:28 | INFO | stdout | [32mINFO[0m:     127.0.0.1:44806 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33704 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:32 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33714 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:34 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33730 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:36 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33738 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:56 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34888 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:28:59 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33850 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:30:23 | ERROR | stderr | /home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/pydantic/main.py:347: UserWarning: Pydantic serializer warnings:
2024-06-20 12:30:23 | ERROR | stderr |   Expected `str` but got `bool` - serialized value may not be as expected
2024-06-20 12:30:23 | ERROR | stderr |   return self.__pydantic_serializer__.to_python(
2024-06-20 12:30:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:38866 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 12:30:28 | INFO | stdout | [32mINFO[0m:     127.0.0.1:38866 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:28 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:28 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:28 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:28 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     raise exc
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:28 | ERROR | stderr |     raise exc
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:28 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:28 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:28 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:28 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:28 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:28 | ERROR | stderr |     raise exc
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:28 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:28 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:28 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:28 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:28 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:28 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:28 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:28 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:28 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:28 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:28 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:28 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:28 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:29 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50360 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:29 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:29 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:29 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:29 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     raise exc
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:29 | ERROR | stderr |     raise exc
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:29 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:29 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:29 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:29 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:29 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:29 | ERROR | stderr |     raise exc
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:29 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:29 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:29 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:29 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:29 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:29 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:29 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:29 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:29 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:29 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:29 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:29 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:29 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:29 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50364 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:31 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:31 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:31 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:31 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     raise exc
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:31 | ERROR | stderr |     raise exc
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:31 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:31 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:31 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:31 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:31 | ERROR | stderr |     raise exc
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:31 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:31 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:31 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:31 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:31 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:31 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:31 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:31 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:31 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:31 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:31 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:31 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:31 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:31 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:37 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50368 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 12:30:38 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50368 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:38 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:38 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:38 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:38 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     raise exc
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:38 | ERROR | stderr |     raise exc
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:38 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:38 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:38 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:38 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:38 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:38 | ERROR | stderr |     raise exc
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:38 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:38 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:38 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:38 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:38 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:38 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:38 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:38 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:38 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:38 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:38 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:38 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:38 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:38 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:39 | INFO | stdout | [32mINFO[0m:     127.0.0.1:39602 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:39 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:39 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:39 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:39 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     raise exc
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:39 | ERROR | stderr |     raise exc
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:39 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:39 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:39 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:39 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:39 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:39 | ERROR | stderr |     raise exc
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:39 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:39 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:39 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:39 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:39 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:39 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:39 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:39 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:39 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:39 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:39 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:39 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:39 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:39 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:41 | INFO | stdout | [32mINFO[0m:     127.0.0.1:39608 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-06-20 12:30:41 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-06-20 12:30:41 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-20 12:30:41 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-20 12:30:41 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     raise exc
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:41 | ERROR | stderr |     raise exc
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:41 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-20 12:30:41 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-20 12:30:41 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-20 12:30:41 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-20 12:30:41 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-20 12:30:41 | ERROR | stderr |     raise exc
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-20 12:30:41 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-20 12:30:41 | ERROR | stderr |     response = await func(request)
2024-06-20 12:30:41 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-20 12:30:41 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-20 12:30:41 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-20 12:30:41 | ERROR | stderr |     return await dependant.call(**values)
2024-06-20 12:30:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 423, in create_chat_completion
2024-06-20 12:30:41 | ERROR | stderr |     gen_params = await get_gen_params(
2024-06-20 12:30:41 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 332, in get_gen_params
2024-06-20 12:30:41 | ERROR | stderr |     prompt = conv.get_prompt()
2024-06-20 12:30:41 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/conversation.py", line 170, in get_prompt
2024-06-20 12:30:41 | ERROR | stderr |     ret += f"{message.strip()}<|eot_id|>"
2024-06-20 12:30:41 | ERROR | stderr |               ^^^^^^^^^^^^^
2024-06-20 12:30:41 | ERROR | stderr | AttributeError: 'tuple' object has no attribute 'strip'
2024-06-20 12:30:54 | ERROR | stderr | /home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/pydantic/main.py:347: UserWarning: Pydantic serializer warnings:
2024-06-20 12:30:54 | ERROR | stderr |   Expected `str` but got `bool` - serialized value may not be as expected
2024-06-20 12:30:54 | ERROR | stderr |   return self.__pydantic_serializer__.to_python(
2024-06-20 12:30:54 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33946 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 12:35:16 | INFO | stdout | [32mINFO[0m:     127.0.0.1:49640 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:35:28 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51928 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 12:35:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:40434 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:01:04 | INFO | stdout | [32mINFO[0m:     127.0.0.1:40424 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:01:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:40438 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:02:13 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45914 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:02:42 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42602 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:02:48 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42608 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:02:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:36858 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:06:18 | INFO | stdout | [32mINFO[0m:     127.0.0.1:53636 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:06:38 | INFO | stdout | [32mINFO[0m:     127.0.0.1:55748 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:07:20 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41252 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:07:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41264 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:09:40 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41472 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:09:57 | INFO | stdout | [32mINFO[0m:     127.0.0.1:48068 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:10:09 | INFO | stdout | [32mINFO[0m:     127.0.0.1:48920 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:11:45 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52782 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:12:05 | INFO | stdout | [32mINFO[0m:     127.0.0.1:56366 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:20:17 | INFO | stdout | [32mINFO[0m:     127.0.0.1:36924 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:20:21 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51196 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:22:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33146 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:22:39 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42994 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:22:43 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43010 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:22:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50816 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:38:09 | INFO | stdout | [32mINFO[0m:     127.0.0.1:37984 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:38:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:37994 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:39:07 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45392 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:44:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60452 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:44:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:47634 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:47:05 | INFO | stdout | [32mINFO[0m:     10.254.25.12:36510 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:48:34 | INFO | stdout | [32mINFO[0m:     10.254.25.12:34028 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:48:43 | INFO | stdout | [32mINFO[0m:     10.254.25.12:34426 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:51:15 | INFO | stdout | [32mINFO[0m:     10.254.25.12:33790 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:51:15 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39288 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 13:53:15 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52160 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:53:23 | INFO | stdout | [32mINFO[0m:     10.254.25.12:40840 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 13:59:05 | INFO | stdout | [32mINFO[0m:     127.0.0.1:40062 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:01:42 | INFO | stdout | [32mINFO[0m:     127.0.0.1:56154 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:02:39 | INFO | stdout | [32mINFO[0m:     127.0.0.1:57460 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:03:53 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59844 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:04:02 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59844 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:04:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:42732 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:04:34 | INFO | stdout | [32mINFO[0m:     10.254.25.12:42374 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 14:04:52 | INFO | stdout | [32mINFO[0m:     10.254.25.12:46894 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 14:05:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:44030 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:05:35 | INFO | stdout | [32mINFO[0m:     10.254.25.12:38858 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:05:55 | INFO | stdout | [32mINFO[0m:     127.0.0.1:56550 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:07:14 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43682 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:07:56 | INFO | stdout | [32mINFO[0m:     127.0.0.1:44892 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:10:08 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45956 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:11:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50630 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:11:34 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45504 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:12:11 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59954 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:13:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:54668 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:13:31 | INFO | stdout | [32mINFO[0m:     127.0.0.1:56688 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:13:39 | INFO | stdout | [32mINFO[0m:     127.0.0.1:56688 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:13:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43784 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:14:03 | INFO | stdout | [32mINFO[0m:     127.0.0.1:58272 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:14:18 | INFO | stdout | [32mINFO[0m:     127.0.0.1:58684 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:14:39 | INFO | stdout | [32mINFO[0m:     127.0.0.1:49342 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:14:42 | INFO | stdout | [32mINFO[0m:     127.0.0.1:49342 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37794 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37800 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37804 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37818 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37826 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37838 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37844 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37856 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:17:59 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37858 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 14:26:26 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37222 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:28:13 | INFO | stdout | [32mINFO[0m:     10.254.25.12:42332 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:29:53 | INFO | stdout | [32mINFO[0m:     10.254.25.12:35146 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:30:21 | INFO | stdout | [32mINFO[0m:     10.254.25.12:44378 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:30:43 | INFO | stdout | [32mINFO[0m:     10.254.25.12:50858 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:31:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:33374 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:41:28 | INFO | stdout | [32mINFO[0m:     10.254.25.12:33526 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:41:42 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60356 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:42:53 | INFO | stdout | [32mINFO[0m:     10.254.25.12:48078 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:43:56 | INFO | stdout | [32mINFO[0m:     10.254.25.12:34220 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 14:45:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:40866 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39566 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39574 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39588 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39604 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39612 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39620 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39628 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39638 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39654 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39666 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39676 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39680 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39686 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39690 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39706 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39722 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39728 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:39736 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:51398 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:51412 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:51428 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:51434 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:23:58 | INFO | stdout | [32mINFO[0m:     10.254.25.12:51438 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 15:31:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:40804 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:31:32 | INFO | stdout | [32mINFO[0m:     127.0.0.1:36104 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:31:51 | INFO | stdout | [32mINFO[0m:     127.0.0.1:46820 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:32:15 | INFO | stdout | [32mINFO[0m:     127.0.0.1:35920 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:32:42 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52232 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:32:57 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51000 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:33:29 | INFO | stdout | [32mINFO[0m:     127.0.0.1:39756 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:33:46 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33682 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:34:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41648 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:47:03 | INFO | stdout | [32mINFO[0m:     10.254.25.12:44146 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:47:21 | INFO | stdout | [32mINFO[0m:     10.254.25.12:50866 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:47:50 | INFO | stdout | [32mINFO[0m:     10.254.25.12:43922 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:48:06 | INFO | stdout | [32mINFO[0m:     10.254.25.12:57926 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:48:27 | INFO | stdout | [32mINFO[0m:     10.254.25.12:38884 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:49:18 | INFO | stdout | [32mINFO[0m:     10.254.25.12:41540 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:49:30 | INFO | stdout | [32mINFO[0m:     10.254.25.12:58476 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:49:43 | INFO | stdout | [32mINFO[0m:     10.254.25.12:56294 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:49:54 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33024 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:50:08 | INFO | stdout | [32mINFO[0m:     10.254.25.12:35374 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:50:46 | INFO | stdout | [32mINFO[0m:     10.254.25.12:35502 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:51:04 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37522 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:51:26 | INFO | stdout | [32mINFO[0m:     10.254.25.12:50984 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:51:42 | INFO | stdout | [32mINFO[0m:     10.254.25.12:55556 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:56:19 | INFO | stdout | [32mINFO[0m:     127.0.0.1:32868 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:58:41 | INFO | stdout | [32mINFO[0m:     127.0.0.1:55776 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:58:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:33574 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:59:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:58272 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 15:59:14 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52860 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:01:40 | INFO | stdout | [32mINFO[0m:     127.0.0.1:47760 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:02:29 | INFO | stdout | [32mINFO[0m:     10.254.25.12:50202 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:04:45 | INFO | stdout | [32mINFO[0m:     10.254.25.12:46584 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:20:27 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59008 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:20:44 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34768 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52484 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52486 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52498 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52504 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52512 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52520 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52530 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52534 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52542 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52554 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52562 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52564 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52576 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:37 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52590 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52598 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52602 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52604 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52612 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52618 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52620 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52636 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52650 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52658 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52666 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52674 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52686 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52700 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52716 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52724 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52732 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52748 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52752 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52768 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52776 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52790 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:22:38 | INFO | stdout | [32mINFO[0m:     10.254.25.12:52792 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:32:47 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50314 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:43:09 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 16:43:09 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 16:43:09 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 16:43:09 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m31418[0m]
2024-06-20 16:43:09 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 16:43:09 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 16:43:09 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:43:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 16:43:09 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 16:43:09 | ERROR | stderr | 
2024-06-20 16:43:09 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 16:43:09 | ERROR | stderr | 
2024-06-20 16:43:09 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:43:09 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 16:43:09 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 16:43:09 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 16:43:09 | ERROR | stderr |     server.run()
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 16:43:09 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 16:43:09 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 16:43:09 | ERROR | stderr |     return runner.run(main)
2024-06-20 16:43:09 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 16:43:09 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 16:43:09 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 16:43:09 | ERROR | stderr | KeyboardInterrupt
2024-06-20 16:44:01 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 16:44:01 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m110180[0m]
2024-06-20 16:44:01 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 16:44:01 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 16:44:01 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 16:44:59 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 16:44:59 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 16:44:59 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 16:44:59 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m110180[0m]
2024-06-20 16:44:59 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 16:44:59 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 16:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:44:59 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 16:44:59 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 16:44:59 | ERROR | stderr | 
2024-06-20 16:44:59 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 16:44:59 | ERROR | stderr | 
2024-06-20 16:44:59 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:44:59 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 16:44:59 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 16:44:59 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 16:44:59 | ERROR | stderr |     server.run()
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 16:44:59 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 16:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 16:44:59 | ERROR | stderr |     return runner.run(main)
2024-06-20 16:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 16:44:59 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 16:44:59 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 16:44:59 | ERROR | stderr | KeyboardInterrupt
2024-06-20 16:45:09 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 16:45:09 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m111191[0m]
2024-06-20 16:45:09 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 16:45:09 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 16:45:09 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 16:51:40 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 16:51:40 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 16:51:40 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 16:51:40 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m111191[0m]
2024-06-20 16:51:40 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 16:51:40 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 16:51:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:51:40 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 16:51:40 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 16:51:40 | ERROR | stderr | 
2024-06-20 16:51:40 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 16:51:40 | ERROR | stderr | 
2024-06-20 16:51:40 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:51:40 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 16:51:40 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 16:51:40 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 16:51:40 | ERROR | stderr |     server.run()
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 16:51:40 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 16:51:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 16:51:40 | ERROR | stderr |     return runner.run(main)
2024-06-20 16:51:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 16:51:40 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 16:51:40 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 16:51:40 | ERROR | stderr | KeyboardInterrupt
2024-06-20 16:51:45 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 16:51:45 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m117667[0m]
2024-06-20 16:51:45 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 16:51:45 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 16:51:45 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 16:51:54 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50994 - "[1mGET / HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:51:55 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50994 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 16:53:13 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37462 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 16:53:18 | INFO | stdout | [32mINFO[0m:     10.254.25.12:37462 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 16:53:24 | INFO | stdout | [32mINFO[0m:     10.254.25.12:40378 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2024-06-20 16:53:37 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-20 16:53:37 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-20 16:53:37 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-20 16:53:37 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m117667[0m]
2024-06-20 16:53:37 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-20 16:53:37 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-20 16:53:37 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:53:37 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-20 16:53:37 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-20 16:53:37 | ERROR | stderr | 
2024-06-20 16:53:37 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-20 16:53:37 | ERROR | stderr | 
2024-06-20 16:53:37 | ERROR | stderr | Traceback (most recent call last):
2024-06-20 16:53:37 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-20 16:53:37 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-20 16:53:37 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
2024-06-20 16:53:37 | ERROR | stderr |     server.run()
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-20 16:53:37 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-20 16:53:37 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-20 16:53:37 | ERROR | stderr |     return runner.run(main)
2024-06-20 16:53:37 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-20 16:53:37 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/asyncio/runners.py", line 123, in run
2024-06-20 16:53:37 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-20 16:53:37 | ERROR | stderr | KeyboardInterrupt
2024-06-20 16:53:50 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8005, controller_address='http://localhost:51001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-20 16:53:50 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m122295[0m]
2024-06-20 16:53:50 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-20 16:53:50 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-20 16:53:50 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8005[0m (Press CTRL+C to quit)
2024-06-20 16:57:02 | INFO | stdout | [32mINFO[0m:     10.254.25.12:42422 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 16:59:49 | INFO | stdout | [32mINFO[0m:     10.254.25.12:59596 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60700 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60706 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60720 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60726 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60740 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60754 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60766 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60776 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60778 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60784 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60794 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60810 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60814 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60820 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60822 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60836 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60850 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60856 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60870 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60874 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60886 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60890 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60896 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:40 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60904 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60908 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60914 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60930 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60944 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60952 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60966 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60968 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 17:33:41 | INFO | stdout | [32mINFO[0m:     10.254.25.12:60970 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2024-06-20 19:15:21 | INFO | stdout | [32mINFO[0m:     10.254.25.12:50378 - "[1mGET /v1/chat/completions HTTP/1.1[0m" [31m405 Method Not Allowed[0m
2024-06-20 19:57:55 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52248 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 19:58:10 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52066 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 19:58:20 | INFO | stdout | [32mINFO[0m:     127.0.0.1:39106 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 19:58:43 | INFO | stdout | [32mINFO[0m:     127.0.0.1:46594 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:00:27 | INFO | stdout | [32mINFO[0m:     127.0.0.1:46014 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:01:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:47050 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:01:33 | INFO | stdout | [32mINFO[0m:     127.0.0.1:34100 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:01:42 | INFO | stdout | [32mINFO[0m:     127.0.0.1:50910 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:01:49 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43288 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:01:57 | INFO | stdout | [32mINFO[0m:     127.0.0.1:43294 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:02:23 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41196 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:05:00 | INFO | stdout | [32mINFO[0m:     127.0.0.1:51930 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:05:25 | INFO | stdout | [32mINFO[0m:     127.0.0.1:41954 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:05:38 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45114 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:05:46 | INFO | stdout | [32mINFO[0m:     127.0.0.1:45126 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:06:05 | INFO | stdout | [32mINFO[0m:     127.0.0.1:38152 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-20 20:06:35 | INFO | stdout | [32mINFO[0m:     127.0.0.1:35792 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 10:51:34 | INFO | stdout | [32mINFO[0m:     10.254.25.12:47236 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 10:52:39 | INFO | stdout | [32mINFO[0m:     10.254.25.12:33592 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 10:58:10 | INFO | stdout | [32mINFO[0m:     10.254.25.12:54964 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 10:58:31 | INFO | stdout | [32mINFO[0m:     10.254.25.12:41162 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 11:19:56 | INFO | stdout | [32mINFO[0m:     10.254.25.12:54394 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 11:20:49 | INFO | stdout | [32mINFO[0m:     10.254.25.12:44272 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-06-21 11:22:19 | INFO | stdout | [32mINFO[0m:     10.254.25.12:38102 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
